name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Major Changes'
    labels:
      - 'pr-major'
  - title: 'Features and Minor Changes'
    labels:
      - 'pr-minor'
  - title: 'Bug Fixes and Patches'
    labels:
      - 'pr-patch'
  - title: 'Other'
    labels:
      - 'docs'

include-labels:
  - pr-major
  - pr-minor
  - pr-patch
  - docs
exclude-contributors:
  - github-actions
  - github-actions[bot]

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'pr-major'
  minor:
    labels:
      - 'pr-minor'
  patch:
    labels:
      - 'pr-patch'
  default: patch

template: |
  # Changes

  $CHANGES
