[package]
name = "metallb-dyn6-sources"
version = "0.1.0"
edition = "2021"
description = "Sources for retrieving a dynamic Ipv6 prefix"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.73"
ipnet = "2.8.0"
reqwest = { version = "0.11.20", default-features = false, features = [
    "rustls-tls",
    "json",
] }
serde = { version = "1.0.186", features = ["derive"] }
thiserror = "1.0.47"
