[package]
name = "interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
interfaces = "0.0.9"
ipnet = "2.8.0"
address_source = { path = "../address_source" }
