[package]
name = "prefix_source"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.73"
ipnet = "2.8.0"
thiserror = "1.0.47"
