[package]
name = "metallb-dyn6-k8s"
version = "0.1.0"
edition = "2021"
description = "Manages m8s API access for updating MetalLB resources"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.9.0"
ipnet = "2.8.0"
jsonschema = "0.17.1"
k8s-openapi = { version = "0.19.0", features = ["v1_27", "schemars"] }
kube = { version = "0.85.0", default-features = false, features = [
    "client",
    "rustls-tls",
    "runtime",
    "derive",
    "config",
    "kube-derive",
    "kube-runtime",
] }
schemars = "0.8.13"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
thiserror = "1.0.48"
tracing = { version = "0.1.37" }
