---
name: Prepare a new Release PR

on:
  workflow_dispatch:

jobs:
  prepare-release-pr:
    name: Create release PR
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out codebase
        uses: actions/checkout@v4

      - uses: release-drafter/release-drafter@v5
        id: drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter.yml

      - name: Extract version from release name
        run: echo "RELEASE_VERSION=$(echo ${{ steps.drafter.outputs.name }} | sed 's/chart-v//')" >> $GITHUB_ENV

      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Enable cargo caching
        uses: Swatinem/rust-cache@v2
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3"

      - name: Install cargo-edit
        run: cargo install cargo-edit --locked
      - name: Update cargo version
        run: |
          cargo set-version --workspace "${{ env.RELEASE_VERSION }}"
          cargo update -w

      - name: Update chart version
        working-directory: helm/charts/metallb-dyn6
        run: |
          make version-from-cargo

      - name: Open PR for release
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: |
            Cargo.toml
            Cargo.lock
            helm/charts/**/Chart.yaml
          title: Prepare Release ${{ steps.drafter.outputs.name }}
          body: |
            Steps to release ${{ steps.drafter.outputs.name }}:

            1. Merge this PR. This will update the chart version in the repository.
            2. Publish the created Draft Release [here](${{ steps.drafter.outputs.html_url }})

            Once merged and published, the CI will then package both the app and the Helm charts and upload their assets.
          commit-message: "Release ${{ steps.drafter.outputs.name }}"
          branch: maintenance/release-pr
          labels: chore
          delete-branch: true
